### ISSUE TITLE
The map-loading gets progressively worse every match

### ISSUE THREAD

**Issue by ClobberXD** [rubenwardy/capturetheflag#112]
This is especially evident in 'The Bridge' and 'Cavern' maps - after a player has joined, the map loads fine in the first match, but worsens every match, and 10-15 matches later, it takes 3-4 minutes for the players to even start moving from the spawn-point, at the start. The other players tend to have the exact same experience too...

**Comment by afshaan4** [comment]
Yeah same stuff happening here.

**Comment by ClobberXD** [comment]
This might be related to #100 - I think minetest itself is at fault here - this did not happen when there was only 1 map...

**Comment by afshaan4** [comment]
is the map being cached locally?
Or is every map you've been to being resent to you.
Because the "cave" map is visible from the "bridge" map if you turn on "full viewing range"

Its that thing in the center.

![screenshot from 2018-02-24 14-19-13](https://user-images.githubusercontent.com/20749736/36627945-5954aa3e-1970-11e8-878a-a0c6635b79a8.png)

also when the network reliability is sketchy this happens:
The unloaded parts of the map cant be reached (you cant go to them) and you see through walls.

![1map_not_loading](https://user-images.githubusercontent.com/20749736/36627954-9a63d522-1970-11e8-92a1-759cee919205.png)

**Comment by ClobberXD** [comment]
I dunno about the map caching, but the latter has happened many times - a distant part of the map loads before the chunks in between, and I end up with X-ray vision for the next couple of seconds - this was how I could see you in spite of you hiding 'in the shadows' a few days back... XD
