### ISSUE TITLE
Chests spawn outside of the map

### ISSUE THREAD

**Issue by harrycode** [rubenwardy/capturetheflag#113]
![screenshot from 2018-02-07 20-24-40](https://user-images.githubusercontent.com/6679953/36059152-f6858786-0e7d-11e8-9efe-dfafd759ce71.png)

**Comment by harrycode** [comment]
Is this intentional?

**Comment by afshaan4** [comment]
This isn't a bug, as it's not affecting gameplay  or anything.
>Is this intentional?

No, i think it's just that the chest algorithm doesn't account for boundaries.

**Comment by harrycode** [comment]
Good point. But maybe there's something REALLY good in that chest and we never got to obtain it.

**Comment by afshaan4** [comment]
Yeah, but sometimes they are close enough to take the stuff in them.

**Comment by harrycode** [comment]
How can you take stuff from them if there is a wall of unbreakable glass in between you and the chest?

**Comment by ClobberXD** [comment]
This is not intentional, but neither is this a bug - also, if the chest's are close enough, you can right-click on them, as the ctf_barrier can't be _highlighted_ (sorry I don't have a better word for it) - even if you point at the barrier, the node(s) do not get highlighted. I've even plucked apples from trees on the other side of the barrier...

**Comment by afshaan4** [comment]
A better way to put it is: you can't *select* the barrier, you just select what is beyond it and so you can take the stuff from the chests.

**Comment by ClobberXD** [comment]
Precisely! :+1:

**Comment by rubenwardy** [comment]
Heh, I don't care about this

![](https://geekwhisperin.files.wordpress.com/2009/09/bug-vs-feature.jpg)
