### ISSUE TITLE
Allocate players to teams depending on ranking.

### ISSUE THREAD

**Issue by rubenwardy** [rubenwardy/capturetheflag#37]
- Sort online player by rank.
- Some sort of random swapping/player trading?

**Comment by AKryukov92** [comment]
I think player allocation to team is coded in core ctf_pvp_engine in function https://github.com/rubenwardy/ctf_pvp_engine/blob/e2a59cef6eba80464af5414d89c4e1c6fbfd597c/ctf/teams.lua#L264

**Comment by ClobberXD** [comment]
That was exactly what I was looking at when I received a notification of a new post in this issue... XD

**Comment by rubenwardy** [comment]
For new matches, the place to modify is where it calls autoalloc either in ctf_map or ctf_match, I forgot. The list of players should be sorted based on ranking, then slightly randomised some how

**Comment by AKryukov92** [comment]
> The list of players should be sorted based on ranking, then slightly randomised some how

I don't think this is that easy, because players are able to join and to leave team in the middle of the fight. For such players it is better to allocate them to team with minimal total score of its members. In case of huge difference between scores of different players, we can use logarithm of score.

**Comment by ClobberXD** [comment]
> The list of players should be sorted based on ranking, then slightly randomised some how

The players also shouldn't be allowed to switch teams in the middle of a match - they should be locked to one team, for the duration of the whole match.

**Comment by AKryukov92** [comment]
> If any new players join, they'll be allocated to the team with a lower cumulative score, and their names added to the aforementioned 'list'.

It can possibly lead to abuse:
* Pro player A joins to game first time in the match and gets allocated to Red because this team is weaker.
* Pro player A logs off. Red team has lower cumulative score again
* Pro player B, friend of A, joins to game first time and gets allocated to Red team again.
* Pro player A logs in and gets returned to red team because he was saved in this team list

**Comment by ClobberXD** [comment]
@rubenwardy Re-open please! :)

**Comment by rubenwardy** [comment]
This has been implemented

**Comment by ClobberXD** [comment]
But we've already discussed that it doesn't work; unless you've had another go at modifying the code...
