### ISSUE TITLE
Score based on skill level of opponents

### ISSUE THREAD

**Issue by rubenwardy** [rubenwardy/capturetheflag#42]
Just killing noobs shouldn't get you many points.

**Comment by Dragonop** [comment]
What about keeping track of how much time a player is alive, and when somebody kills it gets a certain number of points based on such time?

**Comment by ObaniGemini** [comment]
@Dragonop : I think it would be very demanding on server ressources. Also because this would require action_timers mod which is pretty demanding. And having timers on all players all the time would surely be a lag-machine.

I was more thinking, in the same way, but with the kill counter. The more a player gets killed, the less he is valuable in score.

Maybe a function like :
`(1/(xkilled/32))/2` (for it never reaches the 0)               *or*
`0.25*xkilled + 16` with if `result` <1 `result` =1

**Comment by asl97** [comment]
@ObaniGemini not at all, you just have to think outside the box,

just use a player-time table (hashmap/dict).

when the player join, store that time in the table.
when the player get kill, override that time in the table after adding `current_time - table[player]` to the killer score.

**Comment by asl97** [comment]
to be merge with last comment
____
also, your first function doesn't really scale cross lots of matches, after a while, all player would end up only worth 1 point.

your second function add more worth to player who get killed the most

**Comment by rubenwardy** [comment]
https://github.com/rubenwardy/capturetheflag/commit/2234a59c61db500a24a722a9649d1b2aa3124406
