### ISSUE TITLE
It is possible to carry item to next round

### ISSUE THREAD

**Issue by AKryukov92** [rubenwardy/capturetheflag#92]
Steps to reproduce.
When you see flag carrier is near own base:
1) open crafting inventory
2) put items to crafting grid (for example for diamond sword)
3) click on crafting result, but don't put item to inventory
4) wait till round ends
5) open inventory
6) put crafted item to inventory
This is how you can get diamond sword in The Bridge map

**Comment by afshaan4** [comment]
It still works and  is being abused a lot.

Behold a Mese sword in the bridge map:

![screenshot from 2018-02-06 12-54-50](https://user-images.githubusercontent.com/20749736/35846777-fc51aebc-0b3d-11e8-9eef-88a55690ecd0.png)

**Comment by ClobberXD** [comment]
To clarify:
 - When you click the output slot of the crafting grid, the item sticks to the cursor.
 - It disappears when the end-of-match scores table is displayed.
 - When the inventory is opened the next match, lo and behold, the item is still sticking to the cursor!
 - You can now place it in your inventory!

This bug is being continually exploited by players, every time the match in the cavern map ends.

**Comment by farooqkz** [comment]
Is it a good idea to delete an item if it's not in the set of current map's items?
(e.g. just underground map has mese sword)

**Comment by afshaan4** [comment]
That might be a viable solution, but it won't fix the underlying bug, ideally the bug itself should be fixed.

Maybe the items in the players "hand" has to be purged.

**Comment by farooqkz** [comment]
I never said it fixes the problem, but it's a temporary solution. I also like to punish the player because they've done such a job.

**Comment by rubenwardy** [comment]
Fixed

**Comment by ClobberXD** [comment]
@rubenwardy Which commit(s) is responsible for fixing this? The new crafting mod itself?
